[package]
name = "from_rtlsdr"
version = "0.1.0"
edition = "2024"

[dependencies]
dsp-tools = { git = "https://github.com/garbagetrash/dsp-tools.git" }
dsp-rtlsdr-rs = { path = "../dsp-rtlsdr-rs" }

clap = { version = "4.5", features = ["derive"] }
num-complex = "0.4"
anyhow = "1"
bytemuck = "1"
